CREATE TABLE user_otps (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,

  otp_code VARCHAR(255) NOT NULL,
  expires_at DATETIME NOT NULL,
  is_used BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (user_id) REFERENCES users(id)
    ON DELETE CASCADE
);